### ISSUE TITLE
Handle multiple procedures with separate dates

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/data_schema#12]
Right now the `surgery` schema has a single top-level object with a date. How do I represent two different procedures on different dates, e.g. a retro-orbital injection on one date, perfusion on another, clearing on another?

**Comment by dyf** [comment]
Proposal: make a general `procedures` array within `mouse` that is a list of surgeries and other procedures that can each have their own subschema.

**Comment by saskiad** [comment]
Procedures.json allows multiple procedures, each with its own date, etc.
