### ISSUE TITLE
Revise schemas to separate display name from database name

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/data_schema#16]
Downstream databases need to know how to name tables and columns, but the current schema key convention differs from database naming best practices. Our schema should separate internal keys from display names.

The convention we are adopting:

- [snake case](https://en.wikipedia.org/wiki/Snake_case) for internal keys 
- [sentence case](https://apastyle.apa.org/style-grammar-guidelines/capitalization/sentence-case) for display names 

Acceptance criteria

- [x] All schema are updated to the above convention.
- [x] All schema have updated version numbers.
- [ ] All examples are updated.

**Comment by dyf** [comment]
pretty sure this is done now

**Comment by dyf** [comment]
I was wrong, instrument example needs to be cleaned up

**Comment by saskiad** [comment]
instrument looks good to me. The only thing outstanding here, to my knowledge, is fixing the examples.
