### ISSUE TITLE
Add github action to run jsonschema validator

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/data_schema#33]
Acceptance Criteria:

- [ ] When a PR is open, a github action runs that ensures that all examples in the repo validate against the latest version of the schema

**Comment by aricAI** [comment]
Do we have an existing script that performs this validation?

**Comment by jtyoung84** [comment]
Originally, I had some python code combined together with this repo, but we decided to make this a repo purely for json. Although, we might revert and generate the json schema from pydantic. My old code I used is stored here: 
https://github.com/AllenNeuralDynamics/aind-metadata-example-generator/blob/main/tests/test_validations.py

We might be able to hold off on this until we settle on whether we're going to convert these into pydantic classes.

**Comment by jtyoung84** [comment]
It looks like if we import jsonschema, we can check an instance against a schema from the command line. For example,
`jsonschema --instance example/subject.json schemas/subject.json`
from the library: https://pypi.org/project/jsonschema/

**Comment by dyf** [comment]
Moving this to the new `aind-data-schema` repo.
