### ISSUE TITLE
Schemas not validating

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/data_schema#7]
I've been checking these with a python script. I can fix these and add that script in a small unit test library if wanted.

Surgery Schema.json: line 58
Ephys Session Schema.json: line 73, "Session Types" should be "Session Type" 
Ephys Session alternate schema.json: line 164
Ephys Session alternate schema.json: line 172, "Session Types" should be "Session Type"
Instrument Schema.json: "int" should be "integer"
Instrument Schema.json: "Microscope Manufacturer" and "Microscope Model" are duplicated in the required list

**Comment by saskiad** [comment]
Thanks! I'll fix these.
If you can add the script, that would be great. Thank you!

**Comment by saskiad** [comment]
I think I got them all - lmk if I missed anything.
